name: renovate-config:renovate

on:
  schedule:
    - cron: "0 15 * * *"
  repository_dispatch:
    types:
      - trigger-heyhoe-renovate
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      RENOVATE_VERSION: "42.66.4"
      BASE_DIR: /tmp/renovate
      CACHE_DIR: /tmp/renovate/cache/renovate/repository

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RENOVATE_GITHUB_APP_ID }}
          private-key: ${{ secrets.RENOVATE_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get date for cache key
        id: cache-key
        run: |
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Renovate repository cache
        uses: actions/cache@v5
        continue-on-error: true
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-renovate-cache-${{ steps.cache-key.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-renovate-cache-

      - name: Set cache permissions
        id: permissions
        run: |
          mkdir -p "$BASE_DIR"
          # see: https://github.com/renovatebot/renovate/blob/46d75d3c3f8c743dff3c61847cea2cd6f1cc9362/tools/docker/Dockerfile#L121
          sudo chown -R "12021:$(id -g)" "$BASE_DIR"

      - name: Run renovate
        uses: renovatebot/github-action@eaf12548c13069dcc28bb75c4ee4610cdbe400c5 # v44.2.6
        with:
          renovate-version: ${{ env.RENOVATE_VERSION }}
          configurationFile: .github/renovate-config.json
          docker-cmd-file: .github/renovate-entrypoint.sh
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_REPOSITORY_CACHE: enabled
