name: renovate-config:validate

on:
  push:
    paths:
      - "**/*.json"
      - ".github/workflows/_validate.yaml"
      - ".github/workflows/validator.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "**/*.json"
      - ".github/workflows/_validate.yaml"
      - ".github/workflows/validator.yaml"

jobs:
  validate:
    uses: ./.github/workflows/validator.yaml
    with:
      config_files: "**/*.json"
