name: renovate-config:validate

on:
  push:
    paths:
      - ".github/**"
      - "**/*.json"
    branches:
      - main
  pull_request:
    paths:
      - ".github/**"
      - "**/*.json"

jobs:
  validate:
    uses: ./.github/workflows/validator.yaml
    with:
      config_files: "**/*.json"
